### ISSUE TITLE
请问特征字串是怎么查到的？谢谢

### ISSUE THREAD

**Issue by kingmo888** [MrXiaoM/WeChatMessages#2]
仔细阅读了博客文章，也依葫芦画瓢找到了地址，
先射箭后画靶没问题，但是从哪里知道要搜索字符串“OnSyncAppMsgAdd”呢？
WeChatFerry 项目上好像也没有这个字符串特征。

**Comment by MrXiaoM** [comment]
先射箭后画靶，我先根据 WeChatFerry 提供的地址 `0x2205510` 找到接收消息的函数是  `sub_182205510`，在里面调用的一个函数里找到了这个字符串。搜索发现只有这个函数使用了这个字符串，所以可以将其作为字符串特征反过来找到这个函数。

**Comment by MrXiaoM** [comment]
微信能有这么多字符串特征的原因是，它自己会打印日志，打印到它们加密的文件里，这些字符串都是日志的一部分。

**Comment by kingmo888** [comment]
> 先射箭后画靶，我先根据 WeChatFerry 提供的地址 `0x2205510` 找到接收消息的函数是 `sub_182205510`，在里面调用的一个函数里找到了这个字符串。搜索发现只有这个函数使用了这个字符串，所以可以将其作为字符串特征反过来找到这个函数。

感谢作者。
这思路学到了。
也就是等于开一个原项目相同的wechat和ida分析，然后另开自己想用的目标版本，找对应数据。

**Comment by kingmo888** [comment]
> 微信能有这么多字符串特征的原因是，它自己会打印日志，打印到它们加密的文件里，这些字符串都是日志的一部分。

原来这是网上很多资料中的hook微信日志的作用啊。一直没当回事。最近刚阅读了本项目后，又研究dbg方式找这个地址，打了断点是经常假死，完全没招。

**Comment by kingmo888** [comment]
麻烦再咨询下，我发现在已知字符串的时候倒推交叉引用可以找到字符串定义所在函数。但是反过来却找不到。

以博客文末sub_182141E80为例，找到该地址后，查看引用，最多只能进入到这一层：
![image](https://github.com/user-attachments/assets/35a0099f-72f8-4679-badc-4676210d615a)
它的伪代码是：
![image](https://github.com/user-attachments/assets/2209d410-e860-4ba8-a701-7f3e2c5bbb50)

继续找引用就找不到了。未发现OnSyncAppMsgAdd相关字符串

能详细介绍下吗？谢谢

**Comment by MrXiaoM** [comment]
我是在 `3.9.10.27` 的 `sub_182205510` 里面点 F5 生成伪代码，翻一遍，找不到能作为特征唯一的字符串 (`notifymessage` 用不了，很多地方都有，要配合下一句的 `= 13` 才能判别)，  
就一个一个函数点进去看，发现某一个函数里面有 `AppMsgMgr::OnSyncAppMsgAdd`，并且全局搜索没有找到其它函数有调用这个字符串常量，就能通过搜索这个字符串反查到这个函数。
说白了，就是前人（WeChatFerry）已经帮我们找好点位了，我们只需要到那个点位去找不变的东西作为特征，然后再去新版本看看找不找得到一样的。

**Comment by MrXiaoM** [comment]
在这个例子中，找到特征字符串这个过程不需要查找“交叉引用列表”，查找交叉引用是往上翻看看谁调用过这个函数/变量的。
而这个字符串在这个函数调用的某个函数里。

**Comment by kingmo888** [comment]
学习了。相当于直接在目标函数里各种摸索吧。
我继续摸索摸索，尝试看看能不能在12.17上重新走这个路。非常感谢。

**Comment by kingmo888** [comment]
再次感谢。
![image](https://github.com/user-attachments/assets/205d2265-95e9-4915-9342-40def575e92e)

![image](https://github.com/user-attachments/assets/d25d7b7e-b3ea-4c9c-b264-327b61b83cd7)
